version: '2'
services:
  app:
    container_name: webserver-csharp
    build: .
    # expose: [ "8080" ]
    ports: [ "8080:8080" ]
    restart: always
    networks:
      csharp-test:
        ipv4_address: 172.35.0.2

networks:
  csharp-test:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.35.0.0/24
        gateway: 172.35.0.1